### ISSUE TITLE
ROS 2 Crystal build failing on arm64

### ISSUE THREAD

**Issue by nuclearsandwich** [mrpt-ros2-pkg-release/mrpt2-release#1]
@jolting I wasn't sure if this release is supported by upstream MRPT so I've opened the issue here for now, but I can open one upstream if it would be welcome.

The mrpt2 build for ROS 2 Crystal is [currently failing](http://build.ros2.org/job/Cbin_ubv8_uBv8__mrpt2__ubuntu_bionic_arm64__binary/92/console).  It would be great if you could investigate the build failure and either make a follow-up release fixing the build or report an issue on ros-infrastructure/ros_buildfarm if you believe the build farm is at fault.

**Comment by jolting** [comment]
Sure I'll take a look.

**Comment by nuclearsandwich** [comment]
I have opened [a pull request](https://github.com/ros2/ros_buildfarm_config/pull/41) blacklisting this package on the failing architecture. Since Crystal is going to reach the end of its support lifecycle in December I would suggest not worrying about this issue. If you're interested in releasing the packages into Dashing that would be an opportunity to resolve the armv8 issues.

**Comment by jolting** [comment]
Sure.
MRPT 2.0 is alpha status right now and I was hoping for an official release before pushing again.
The ARMv8 fix is already merged upstream. I have access to a Jetson AGX now. 
Thanks for the help.

**Comment by nuclearsandwich** [comment]
@jolting you're naturally welcome to release fixes into Crystal and I'm happy to merge them until the end of support, but if you're looking to maximize economy of effort focusing on the Dashing release is the way to go.
